name: CI Pipeline

on:
  push:
    branches:
      - dev
      - test
      - main
  pull_request:
    branches:
      - dev
      - test
      - main

jobs:
  build:
    name: Build Next.js Application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: "latest"

      - name: Install dependencies
        run: bun install

      - name: Lint with Biome
        run: bun run lint
        continue-on-error: false

      - name: Format check with Biome
        run: bun biome format --check .
        continue-on-error: true

      - name: Build Next.js
        run: bun run build